version: "2"

services:
  php:
    image: 'eboraas/laravel'
    links:
      - mysql:mysql
    volumes: 
      - ./:/var/www/laravel
    ports:
      - 8080:80
      - 8000:8000

  mysql:
    image: 'mysql/mysql-server:latest'
    restart: 'always'
    environment:
      MYSQL_DATABASE: centurydb
      MYSQL_USER: century
      MYSQL_PASSWORD: 1234
      MYSQL_ROOT_PASSWORD: 1234
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - 3306:3306

  apache:
    image: 'ctala/apache2_php7_awsebs'
    links:
      - php:php
    volumes: 
      - ./:/var/www/laravel

  # apache:
  #   image: 'eboraas/laravel'
  #   links:
  #     - php: php
  #   volumenes:
  #     - ./:/var/www/html/

